name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ubuntu
        KEY_FILE: ${{ secrets.KEY_FILE }}

      run: |
        echo "${{ secrets.KEY_FILE }}" > sample.pem
        chmod 400 sample.pem

        # Ensure directory creation and permissions are set correctly
        ssh -i sample.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'sudo mkdir -p /home/$EC2_USER/my-node-app && sudo chown -R $EC2_USER:$EC2_USER /home/$EC2_USER/my-node-app && ls -la /home/$EC2_USER'

        scp -i sample.pem -o StrictHostKeyChecking=no package.json package-lock.json app.js $EC2_USER@$EC2_HOST:/home/$EC2_USER/my-node-app/
        scp -i sample.pem -o StrictHostKeyChecking=no -r public $EC2_USER@$EC2_HOST:/home/$EC2_USER/my-node-app/
        scp -i sample.pem -o StrictHostKeyChecking=no -r src $EC2_USER@$EC2_HOST:/home/$EC2_USER/my-node-app/


        # SSH into the EC2 instance to install dependencies and start the application
        ssh -i sample.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          cd /home/$EC2_USER/my-node-app
          npm install
          pm2 restart all || pm2 start app.js
        EOF
