name: Deploy App to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ubuntu
        KEY_FILE: ${{ secrets.KEY_FILE }}

      run: |
        sudo scp -i $KEY_FILE -o StrictHostKeyChecking=no -r . $EC2_USER@$EC2_HOST:/home/ec2-user/my-node-app
        ssh -i $KEY_FILE -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'cd /home/ec2-user/my-node-app && npm install && pm2 restart all || pm2 start app.js'
